apiVersion: v1
kind: Service
metadata:
  name: ngnix-cluster-ip
spec:
  type: clusterIP
  selector:
    app: my-app

  ports:
    - port: 
      - port: 8080 #Service port
        targetPort: 80 #pod/container port