apiVersion: apps/v1
kind: Deployment
metadata:
  name: app
spec:
  replicas: 3
  selector: 
    matchLabels: 
      app: my-app 
  template: 
    metadata:
      name: my-app
      labels:
        app: my-app
    spec:
      containers:
        - name: nginx-image
          image: os2003/nginx-test
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80