apiVersion: v1
kind: Service
metadata:
  name: node-port-service
spec:
  type: NodePort
  selector:
    app: my-app

  ports:
     - port: 8080 #Service port
       targetPort: 80 #pod/container port
       nodePort: 30005 #Any port between 30000 and 32767